# Server port (change if 8080 is busy)
server.port=9090

# Application name
spring.application.name=selenium-demo

# Location of Extent report output
extent.reporter.spark.start=true
#extent.reporter.spark.out=target/ExtentSparkReport/extent.html
#extent.reporter.spark.config=src/test/resources/extent-config.xml
extent.reporter.spark.config=extent-config.xml
extent.reporter.spark.out=extent.html

# Custom system info for reports
systeminfo.user=Rakesh Anand
systeminfo.project=Selenium Demo
systeminfo.build=1.0.0
systeminfo.environment=QA
systeminfo.browser=Chrome
systeminfo.platform=Windows 10

# Absolute path to your Extent JSON file
extent.json.path=../reports/extent.json


# H2 Database Connection (creates a file named 'testdb' in your project root)
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 Console for debugging via browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Allows the console to be viewed if you are using frames
spring.headers.frame-options=sameorigin



