# Server port (change if 8080 is busy)
server.port=9090

# Application name
spring.application.name=selenium-demo

# Location of Extent report output
extent.reporter.spark.start=true
#extent.reporter.spark.out=target/ExtentSparkReport/extent.html
#extent.reporter.spark.config=src/test/resources/extent-config.xml
extent.reporter.spark.config=extent-config.xml
extent.reporter.spark.out=extent.html

# Custom system info for reports
systeminfo.user=Rakesh Anand
systeminfo.project=Selenium Demo
systeminfo.build=1.0.0
systeminfo.environment=QA
systeminfo.browser=Chrome
systeminfo.platform=Windows 10

# Absolute path to your Extent JSON file
extent.json.path=../reports/extent.json



