extent.reporter.spark.start=true
extent.reporter.spark.out=../reports/extent.html

# This is the line that generates the data for your dashboard
extent.reporter.json.start=true
extent.reporter.json.out=../reports/extent.json

# Ensures the report writes even if the JVM exits abruptly
screenshot.dir=../reports/screenshots/
screenshot.rel.path=../reports/screenshots/


# System info
systeminfo.user=Rakesh Anand
systeminfo.project=Selenium Demo
systeminfo.build=1.0.0
systeminfo.environment=QA
systeminfo.browser=Chrome
systeminfo.platform=Windows 10
